<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_var</name>
   <tag></tag>
   <elementGuidId>822323ce-5d1b-4a23-b5f5-4384d8d834a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[text()='${text}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[text()='${text}']</value>
      <webElementGuid>9530fe06-24f9-4312-bf2f-42d3d2f156e4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
