<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_main_header_txt-var</name>
   <tag></tag>
   <elementGuidId>ef8ffdbe-4ec0-4ae3-9cad-19663e2e6811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='main-header']/self::div[text()='${nama_main_header}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='main-header']/self::div[text()='${nama_main_header}']</value>
      <webElementGuid>e436ed05-848b-49f9-b5dc-08e00efaabc4</webElementGuid>
   </webElementProperties>
</WebElementEntity>
