<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ipt_field_id-var</name>
   <tag></tag>
   <elementGuidId>595cb7bb-e598-45fe-b939-b4b86c4a15d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='${field}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='${field}']</value>
      <webElementGuid>36bd3368-cc2d-4c9b-b0cb-c5ca57ac7f57</webElementGuid>
   </webElementProperties>
</WebElementEntity>
