<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_next</name>
   <tag></tag>
   <elementGuidId>2a3787e5-8080-43a7-8cc3-915c0ba2d60f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id='app']/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/div[3]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id='app']/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/div[3]/button</value>
      <webElementGuid>57984669-c8af-4708-ba9e-df54ebe94be9</webElementGuid>
   </webElementProperties>
</WebElementEntity>
