<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pagination</name>
   <tag></tag>
   <elementGuidId>d2a7abf1-d64c-48f0-ac4f-b8bed71a79e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/div[2]/span[1]/div/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/div/div[2]/span[1]/div/input</value>
      <webElementGuid>1c7f7a1c-af3b-459a-b12a-51b0cba281dd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
