<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>login_page_btn</name>
   <tag></tag>
   <elementGuidId>c158ce59-e531-4d5a-8f90-194a66f5b858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='login']</value>
      <webElementGuid>95373e20-cd79-4fd6-8978-ac0995e459f5</webElementGuid>
   </webElementProperties>
</WebElementEntity>
