<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_ToolsQA</name>
   <tag></tag>
   <elementGuidId>08161397-9c3f-45d2-a493-11503a8a4a82</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;app&quot;]/header/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;app&quot;]/header/a/img</value>
      <webElementGuid>0c4a4462-e82f-485e-a115-ee3f7af536c7</webElementGuid>
   </webElementProperties>
</WebElementEntity>
