<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>verify_page_login</name>
   <tag></tag>
   <elementGuidId>87cc1b10-0b53-4773-b6b9-26edbb8c24cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@class='profile-wrapper']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[@class='profile-wrapper']</value>
      <webElementGuid>b96eae70-f1fc-464f-8112-25d341872b5b</webElementGuid>
   </webElementProperties>
</WebElementEntity>
