<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_data_mel</name>
   <tag></tag>
   <elementGuidId>3551cb55-5e70-4b52-944d-ddd10cafaa9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='${isi}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='${isi}']</value>
      <webElementGuid>e64f03c6-71f5-4fcb-8c6b-9125758ad15e</webElementGuid>
   </webElementProperties>
</WebElementEntity>
