<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tombol_submit_mel</name>
   <tag></tag>
   <elementGuidId>c6c17b20-f51e-43bd-99c0-b3fb808f14dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//button[@id='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//button[@id='submit']</value>
      <webElementGuid>79697b3a-7c9a-4753-923d-b121c97e3590</webElementGuid>
   </webElementProperties>
</WebElementEntity>
